# Generated by Django 6.0 on 2026-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KANISDOG', max_length=120, verbose_name='Название сайта')),
                ('hero_text', models.TextField(blank=True, verbose_name='Текст (Hero)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Картинка (Hero)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
    ]
