# Generated by Django 6.0.1 on 2026-01-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='specialists/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(max_length=100, verbose_name='Должность')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
                ('breed', models.CharField(help_text='Если специалист работает с собакой', max_length=100, verbose_name='Порода собаки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['order'],
            },
        ),
    ]
