# Generated by Django 6.0.1 on 2026-01-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dogs/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('character', models.CharField(max_length=255, verbose_name='Характер')),
                ('likes', models.CharField(max_length=255, verbose_name='Что любит')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='core.specialist', verbose_name='Специалист (хозяин)')),
            ],
            options={
                'verbose_name': 'Собака-терапевт',
                'verbose_name_plural': 'Собаки-терапевты',
                'ordering': ['order'],
            },
        ),
    ]
