# Generated by Django 6.0.1 on 2026-01-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('parent', 'Отзывы родителей'), ('adult', 'Отзывы взрослых'), ('result', 'Результаты')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age_info', models.CharField(blank=True, help_text='Например: 7 лет', max_length=100, verbose_name='Возраст (ребенка/клиента)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв / Результат',
                'verbose_name_plural': 'Отзывы и Результаты',
            },
        ),
    ]
